### PR TITLE
Generic repository

### PR DESCRIPTION
**Pull request by leodido**
Introduction of a generic repository template.

Via a go generate tool - ie., genny - we can now generate specific repository implementations.

This way we reduce code duplication without affecting run-time execution (since the generation is done at compile time there is not run-time overhead).

Furthermore we give to each repository its own locking mechanism for its items.

Finally this PR also introduces a simple mechanism to get the identifier of each resource.

Prior to merge this, if we all agree, we should refactor (on this feature branch) the existing repository usage.

### CODE REVIEW

**Comment by leodido** [comment]
Refactoring done.

Tomorrow I'll complete tests for concrete repositories.

Then we can merge.

@fabbricadigitale/webcomponents do not forget to run go generate within the _schemas_ directory.

**Comment by leodido** [comment]
## About the ADD method

### Signature

Testing the code and reviewing it I came to the conclusion that an interface like the following one is better.

```go
type GenericRepository interface {
	...
	Add(filename string) (Elem, error)
}
```

In words.

The `Add` method should return a copy of the generic elem (ie., `core.Schema` or `core.RespourceType` and so on) just inserted within its repository.

Currently it only returns an error (or nil).

What do you think about?

### Strictness

Since the behavior of the unmarshal is to ignore fields it does not find currently the concrete `Add` method of a `SchemaRepository` can get any JSON - eg., one representing a service provider config, so not a schema - populating two or three fields but storing it within the `SchemaRepository` anyway.

Any idea about this behavior?
Should we limit or avoid it?

I'm biased toward avoiding it, if possibile.

cc @leogr, @alelb

**Comment by leogr** [comment]
### Signature
I agree about the method signature (IMHO it's useful, but not priority so we could postpone this task).

### Strictness
In my opinion, the only repo's responsibility is to check that's the item is identifiable so that can be added to the repo itself safely. JSON validation is out of this scope and MUST be handled elsewhere.

**Review by leogr — CHANGES_REQUESTED** [review]
`Add` should check that item's id is not `nil`, so it can be added to the repo safely.

**Comment by leodido** [comment]
Agree, thanks.

Anyway done both hours ago. I am finishing the tests.

**Review by leogr — APPROVED** [review]
LGTM

**Pull request merged**
