### PR TITLE
Custom validator to check for unique attributes

### PR DESCRIPTION
**Pull request by samechelon**
This PR introduces the uniquefield validator that checks if a field in a slice has unique values

### CODE REVIEW

**Review by leogr — CHANGES_REQUESTED** [review]
LGTM, but there's no description that it works with strings only and performs a [**case-insensitive**](https://github.com/fabbricadigitale/scimd/pull/50/files#diff-a0c876f85af836865cdff71b00ab1654R38) comparison. Add some comments pls.

or may we change its name? cc @leodido

**Review by leogr — APPROVED** [review]
LGTM

**Comment by leodido** [comment]
Please rename it to something like `uniqueattr`.

**Review by leodido — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
